// src/constants/careers.js

export const JOB_DEPARTMENTS = ["All", "Engineering", "Marketing", "Design", "Support"];

export const JOBS = [
  {
    id: "react-developer",
    title: "React.js Developer",
    department: "Engineering",
    type: "Full-time",
    mode: "Remote",
    location: "Hyderabad, India / Remote",
    experience: "1–3 Years",
    salary: "₹4–8 LPA",
    posted: "2 days ago",
    urgent: true,
    description:
      "We are looking for a skilled React.js developer to join our growing web development team. You will build scalable, performant web applications and collaborate closely with designers and backend engineers.",
    responsibilities: [
      "Develop and maintain React.js web applications",
      "Translate UI/UX designs into clean, responsive code",
      "Integrate RESTful APIs and GraphQL endpoints",
      "Write unit and integration tests (Jest, RTL)",
      "Participate in code reviews and sprint planning",
    ],
    requirements: [
      "Strong proficiency in React.js, Hooks, and Context API",
      "Experience with Tailwind CSS or styled-components",
      "Familiarity with Git, Vite/Webpack",
      "Knowledge of REST APIs and async JavaScript",
    ],
    tags: ["React", "JavaScript", "Tailwind CSS", "REST APIs"],
    color: "#1A7AFF",
    bgColor: "#EEF6FF",
    icon: "💻",
  },
  {
    id: "digital-marketing-executive",
    title: "Digital Marketing Executive",
    department: "Marketing",
    type: "Full-time",
    mode: "On-site",
    location: "Hyderabad, India",
    experience: "1–2 Years",
    salary: "₹3–5 LPA",
    posted: "5 days ago",
    urgent: false,
    description:
      "Drive our digital marketing efforts across SEO, PPC, and social media channels. You will craft data-driven campaigns that generate leads and build brand awareness for our clients.",
    responsibilities: [
      "Plan and execute Google Ads, Meta, and LinkedIn campaigns",
      "Conduct keyword research and on-page SEO optimization",
      "Manage and grow organic social media channels",
      "Track KPIs using Google Analytics and Meta Business Suite",
      "Produce monthly performance reports for stakeholders",
    ],
    requirements: [
      "Experience with Google Ads and Meta Ads Manager",
      "Solid understanding of SEO principles",
      "Proficiency in Google Analytics 4",
      "Strong copywriting and communication skills",
    ],
    tags: ["SEO", "Google Ads", "Meta Ads", "Analytics"],
    color: "#F59E0B",
    bgColor: "#FFFBEB",
    icon: "📣",
  },
  {
    id: "ui-ux-designer",
    title: "UI/UX Designer",
    department: "Design",
    type: "Full-time",
    mode: "Hybrid",
    location: "Hyderabad, India",
    experience: "1–3 Years",
    salary: "₹4–7 LPA",
    posted: "1 week ago",
    urgent: false,
    description:
      "Create beautiful, intuitive interfaces for web and mobile products. Work alongside developers and product managers to define, prototype, and ship experiences users love.",
    responsibilities: [
      "Design wireframes, prototypes, and high-fidelity mockups",
      "Conduct user research and usability testing",
      "Maintain and evolve the design system",
      "Collaborate with frontend developers for handoff",
      "Ensure visual consistency across all products",
    ],
    requirements: [
      "Proficiency in Figma and Adobe XD",
      "Portfolio demonstrating strong UI/UX work",
      "Understanding of responsive and accessible design",
      "Basic knowledge of HTML/CSS is a plus",
    ],
    tags: ["Figma", "UI Design", "UX Research", "Prototyping"],
    color: "#8B5CF6",
    bgColor: "#F5F3FF",
    icon: "🎨",
  },
  {
    id: "node-backend-developer",
    title: "Node.js Backend Developer",
    department: "Engineering",
    type: "Full-time",
    mode: "Remote",
    location: "Remote (India)",
    experience: "2–4 Years",
    salary: "₹6–10 LPA",
    posted: "3 days ago",
    urgent: true,
    description:
      "Build robust, scalable backend services and APIs that power our client applications. You will architect data models, implement business logic, and ensure high availability and performance.",
    responsibilities: [
      "Design and build RESTful and GraphQL APIs with Node.js",
      "Architect scalable MongoDB and PostgreSQL schemas",
      "Implement authentication, authorization, and security best practices",
      "Write comprehensive unit and integration tests",
      "Optimize queries and service performance",
    ],
    requirements: [
      "Strong experience with Node.js and Express / Fastify",
      "Proficiency in MongoDB and PostgreSQL",
      "Experience with JWT, OAuth, and API security",
      "Familiarity with Docker and cloud deployments (AWS/GCP)",
    ],
    tags: ["Node.js", "MongoDB", "REST APIs", "PostgreSQL"],
    color: "#10B981",
    bgColor: "#ECFDF5",
    icon: "⚙️",
  },
  {
    id: "career-counselor",
    title: "IT Career Counselor",
    department: "Support",
    type: "Full-time",
    mode: "On-site",
    location: "Hyderabad, India",
    experience: "2–5 Years",
    salary: "₹4–6 LPA",
    posted: "1 week ago",
    urgent: false,
    description:
      "Guide aspiring IT professionals through their career journey — from resume building to interview preparation and job placement. You'll make a direct, measurable difference in people's careers.",
    responsibilities: [
      "Conduct one-on-one career counseling sessions",
      "Review and optimize resumes and LinkedIn profiles",
      "Run mock technical and HR interview sessions",
      "Connect candidates with placement opportunities",
      "Track placement outcomes and iterate on coaching methods",
    ],
    requirements: [
      "Experience in HR, recruitment, or IT career coaching",
      "Strong understanding of the Indian IT job market",
      "Excellent communication and mentoring skills",
      "Prior experience in tech recruitment is preferred",
    ],
    tags: ["Career Coaching", "HR", "Placement", "Mentoring"],
    color: "#EC4899",
    bgColor: "#FDF2F8",
    icon: "🎯",
  },
  {
    id: "seo-content-writer",
    title: "SEO Content Writer",
    department: "Marketing",
    type: "Part-time",
    mode: "Remote",
    location: "Remote (India)",
    experience: "0–2 Years",
    salary: "₹2–3.5 LPA",
    posted: "4 days ago",
    urgent: false,
    description:
      "Create compelling, SEO-optimised content for our clients across industries. You'll research keywords, craft blog posts, landing pages, and social copy that ranks and converts.",
    responsibilities: [
      "Research and write SEO-optimised blog posts and articles",
      "Create landing page copy, email sequences, and social content",
      "Conduct keyword research using Ahrefs and Semrush",
      "Edit and proofread content for quality and accuracy",
      "Collaborate with the SEO team to hit traffic targets",
    ],
    requirements: [
      "Excellent written English with SEO knowledge",
      "Familiarity with keyword tools (Ahrefs, Semrush, or GSC)",
      "Ability to write across multiple industries and tones",
      "Experience with WordPress or similar CMS is a plus",
    ],
    tags: ["SEO", "Content Writing", "WordPress", "Copywriting"],
    color: "#F59E0B",
    bgColor: "#FFFBEB",
    icon: "✍️",
  },
];

export const CULTURE_PERKS = [
  { icon: "🏠", title: "Remote Friendly",     desc: "Flexible remote and hybrid work options for most roles." },
  { icon: "📈", title: "Career Growth",        desc: "Clear growth paths and regular performance reviews." },
  { icon: "🎓", title: "Learning Budget",      desc: "Annual budget for courses, certifications, and conferences." },
  { icon: "🤝", title: "Collaborative Team",   desc: "A tight-knit, supportive team that celebrates wins together." },
  { icon: "⚕️",  title: "Health Benefits",     desc: "Medical insurance coverage for you and your family." },
  { icon: "⚡", title: "Modern Tech Stack",    desc: "Work with the latest tools, frameworks, and methodologies." },
];
